### ISSUE TITLE
Ruby 2.4 deprecation warnings caused by nokogiri dependency

### ISSUE THREAD

**Issue by tom-lord** [haml/html2haml#74]
Version 2.0.0 of this gem [depends on nokigiri `~>1.6.0`](https://github.com/haml/html2haml/blob/master/html2haml.gemspec#L20), which resolves to `1.6.8.1`.

However, ruby 2.4 deprecation warnings in nokigiri were [fixed in version `1.7.0`](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.md#features).

Can we release a new gem version that loosens this nokigiri dependency condition?

**Comment by amatsuda** [comment]
Duplicates to #73. Stay tuned!
