### ISSUE TITLE
Update Nokogiri dependency

### ISSUE THREAD

**Issue by mikelkew** [haml/html2haml#78]
Hi there, any chance of relaxing the nokogiri dependency enough to support 1.7.x?

**Comment by oliverklee** [comment]
Hi, there's already PR #73 for this. (It isn't merged yet, though.)

**Comment by mikelkew** [comment]
Oops, sorry @oliverklee, I should have checked. Thank you, I'll keep an eye on it.

**Comment by oliverklee** [comment]
This Issue can be closed now that #73 has been merged, I think.
