### ISSUE TITLE
Haml 5 support

### ISSUE THREAD

**Issue by GuskiS** [haml/html2haml#81]
Please add Haml 5 support in gemfile/code.

**Comment by reubenbrown** [comment]
It appears [this change](https://github.com/haml/html2haml/blob/master/html2haml.gemspec#L24) is not reflected on rubygems

<img width="1184" alt="screenshot 2017-04-30 14 42 07" src="https://cloud.githubusercontent.com/assets/5067334/25567037/3644e6a2-2db3-11e7-920a-3a5865eab164.png">

**Comment by GuskiS** [comment]
It seems that last master changes hasn't released as new version.

**Comment by amatsuda** [comment]
Just released 2.2.0 gem. Thank you! https://rubygems.org/gems/html2haml/versions/2.2.0
